### ISSUE TITLE
[es_MX] Translator access request

### ISSUE THREAD

**Issue by absay** [OpenTTD/team#115]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Spanish (Mexican)**.

The **Spanish (Mexican)** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

I'm the usual (only?) translator of this language but I lost my previous password and when I attempted to log-in to GH and open the translator, it said my access was denied.

Thank you,

Absay

**Comment by DorpsGek** [comment]
Thank you @absay for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @absay is requesting access to language __es_MX__.

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @absay, your request has been approved!
You now have access to es_MX.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before your membership is updated.

You can login to [eints](https://translator.openttd.org/language/es_MX) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/es_MX).

**Comment by absay** [comment]
Thanks.

It keeps saying my access is denied when I try to edit the language. Am I missing something?

**Comment by TrueBrain** [comment]
To quote what @DorpsGek just said:

`
If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click here).
You will have to accept this invitation before your membership is updated.
`

(including a useful link! :D)

You haven't yet, and as such you haven't joined the OpenTTD organization yet. This is an action you have to take before permissions can be assigned :)

**Comment by absay** [comment]
Oh, I'm sorry, I need to learn to read better, lol.

Okay, I have now joined the OpenTTD organization via the link provided by DorpsGek.

**Comment by absay** [comment]
Okay, I have now access to the translator! :D

Thank you very much! And sorry for all the trouble!

**Comment by TrueBrain** [comment]
No worries :) You are not the first to miss that part, and you won't be the last :) GitHub also send an email btw.

If you have tips for us how to make this part more clear, I would love to hear!

Tnx, and enjoy translating :D
