### ISSUE TITLE
Apply labels to access request after approving/denying request

### ISSUE THREAD

**Issue by LordAro** [OpenTTD/team#130]
Useful for reviewing past requests at a glance.

Bonus: Additional label for if the invitation was actually accepted (though that may well be impossible in the current structure)

**Comment by TrueBrain** [comment]
A deny label you can apply yourself; they are so rare, I doubt t is worth the effort to make the bot do this.

This means in extension that anything without a label is an approval.

Good solution until someone picks up this ticket .. if anyone, ever :P

**Comment by frosch123** [comment]
A "deny" always involves some level of drama. Labeling them makes it too easy to find them, and for trolls to feed on them.
