### ISSUE TITLE
[de_DE] Translator access request

### ISSUE THREAD

**Issue by ebla71** [OpenTTD/team#144]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **German**.

The **German** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

As I am a chemist and very much interested in the history of heavy industries and railroads (having grown up in the "Ruhr area" of central Germany) I might be able to contribute to the proper nomenclature in this area.

This is my first registration to GitHub so please allow for a bit of learning curve.

Thank you,

**Comment by DorpsGek** [comment]
Thank you @ebla71 for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @ebla71 is requesting access to language __de_DE__.

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by LordAro** [comment]
/approve

Bear in mind that we already have many German translators (11 signed up) and indeed several of the devs are German as well.

Not to say that there aren't various words that couldn't be improved! You can use the GH teams link that will follow to discuss things with your fellow translators

**Comment by DorpsGek** [comment]
Good news, @ebla71, your request has been approved!
You now have access to de_DE.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before your membership is updated.

You can login to [eints](https://translator.openttd.org/language/de_DE) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/de_DE).
