### ISSUE TITLE
[ko_KR] Translator access request

### ISSUE THREAD

**Issue by telk5093** [OpenTTD/team#15]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Korean**.

The **Korean** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

My recent update is not applied since this migration :(
But I'll do it again, never mind :D

Thank you

**Comment by DorpsGek** [comment]
Thank you @telk5093 for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @telk5093 is requesting access to language __ko_KR__.

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @telk5093, your request has been approved!
You now have access to ko_KR.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before your membership is updated.

You can login to [eints](https://translator.openttd.org/language/ko_KR) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/ko_KR).

**Comment by telk5093** [comment]
@LordAro Sorry for bothering you, it is not still accessible to eints.
When I click string Id, such as ``STR_ABANDON_GAME_CAPTION``, it says still _Access denied_.
Do I have to wait a moment?

**Comment by LordAro** [comment]
Looks like your invite has not been accepted - it is still pending. You need to accept the invite either in the email you should have received, or in the message from DorpsGek above

**Comment by telk5093** [comment]
Oh, there was a invitation message at the top. Thanks.
