### ISSUE TITLE
[lb_LU] Translator access request

### ISSUE THREAD

**Issue by phreeze83** [OpenTTD/team#173]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Luxembourgish**.

The **Luxembourgish** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Thank you,
Hello, i am and was the only translator of the luxembourgish language, i don't know why i get acces denieds now. i don't log in that often, perhaps some acces are revoked upon some time? or i did sth wrong .-/

**Comment by DorpsGek** [comment]
Thank you @phreeze83 for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @phreeze83 is requesting access to language __lb_LU__.

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @phreeze83, your request has been approved!
You now have access to lb_LU.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/lb_LU) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/lb_LU).

**Comment by phreeze83** [comment]
Hello, access is still denied allthough i'm a "team" member of luxembourgish in Github. Or does it take more manual steps from you/me ?

**Comment by frosch123** [comment]
The permissions are read when logging in to eints. 
Just do a logout-login cycle on eints.
