### ISSUE TITLE
[sk_SK] Translator access request

### ISSUE THREAD

**Issue by ApplePie420** [OpenTTD/team#208]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Slovak**.

The **Slovak** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Slovak language is my mother tongue, and I would love to correct some grammar mistakes, spelling and rephrase some sentences that does not give that much sense.
Thank you,
-N3ttX

**Comment by DorpsGek** [comment]
Thank you @ApplePie420 for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @ApplePie420 is requesting access to language [__sk_SK__](https://github.com/orgs/OpenTTD/teams/sk_SK).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @ApplePie420, your request has been approved!
You now have access to sk_SK.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/sk_SK) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/sk_SK).
