### ISSUE TITLE
[da_DK] Translator access request

### ISSUE THREAD

**Issue by beruic** [OpenTTD/team#219]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Danish**.

The **Danish** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Thank you,

**Note:** I missed my chance at https://github.com/OpenTTD/team/issues/204. How long does the invitation last before expiry?

**Comment by DorpsGek** [comment]
Thank you @beruic for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @beruic is requesting access to language [__da_DK__](https://github.com/orgs/OpenTTD/teams/da_DK).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by beruic** [comment]
This was fixed in #204
