### ISSUE TITLE
[pl_PL] Translator access request

### ISSUE THREAD

**Issue by yazalo** [OpenTTD/team#22]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Polish**.

The **Polish** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

I don't come with anything - I have been translating the OpenTTD Wiki for some time (you can see it here: https://wiki.openttd.org/User:Yazalo). There are a few bugs in the Polish version of the game that need to be fixed (the most important ones (in Polish) are listed here: https://openttd-polska.pl/Thread-Zmiany-w-t%C5%82umaczeniu-OTTD?pid=25705#pid25705)

Thank you,

**Comment by DorpsGek** [comment]
Thank you @yazalo for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @yazalo is requesting access to language __pl_PL__.

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @yazalo, your request has been approved!
You now have access to pl_PL.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before your membership is updated.

You can login to [eints](https://translator.openttd.org/language/pl_PL) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/pl_PL).
