### ISSUE TITLE
[en_AU] Translator access request

### ISSUE THREAD

**Issue by SlipperyDuck777** [OpenTTD/team#232]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **English (AU)**.

The **English (AU)** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Hi, I would like to edit the language, I am also familiar with English US, Canadian, and South African dialects. As well as some French (Canadian)

Thank you,

**Comment by DorpsGek** [comment]
Thank you @SlipperyDuck777 for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @SlipperyDuck777 is requesting access to language [__en_AU__](https://github.com/orgs/OpenTTD/teams/en_AU).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @SlipperyDuck777, your request has been approved!
You now have access to en_AU.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/en_AU) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/en_AU).
