### ISSUE TITLE
[cs_CZ] Translator access request [request_access]

### ISSUE THREAD

**Issue by LubosKolouch** [OpenTTD/team#25]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Czech**.

The **Czech** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Thank you,

Luboš

**Comment by LubosKolouch** [comment]
I don't think I can modify the label myself?

**Comment by TrueBrain** [comment]
Hmm .. I wonder what is happening exactly, as the label is missing again. Which is a bit weird, as the template should fill it in. When I create an issue, I see this:

![image](https://user-images.githubusercontent.com/1663690/94793171-593f3300-03da-11eb-8731-b17e4a78a71f.png)

The main point is the label on the right indicating "request_access" in purple. Can you indicate to me how this looks for you? It would greatly help us improve this system if you can :)

Sorry for the trouble, and tnx again.

**Comment by LubosKolouch** [comment]
Hi Patric,

Sure, there are 2 ways I’ve tried it:

1) click on 

Which leads to this :



And then just hitting Submit...

2) Going here:



Which opens the same page (after selecting cs_CZ)...

Cheers,

Lubos

**Comment by TrueBrain** [comment]
Screenshots didn't come through, sadly enough :(

**Comment by LubosKolouch** [comment]
![image](https://user-images.githubusercontent.com/4145223/94794267-e9ca4300-03db-11eb-9f11-a62b7ea7e4bc.jpeg)

**Comment by LubosKolouch** [comment]
![image](https://user-images.githubusercontent.com/4145223/94794310-f8b0f580-03db-11eb-8acb-8e42e553da46.jpeg)

**Comment by LubosKolouch** [comment]
![image](https://user-images.githubusercontent.com/4145223/94794399-154d2d80-03dc-11eb-9875-50fba4aa261f.jpeg)

**Comment by TrueBrain** [comment]
Thank you for the details.

It seems GitHub has rolled out a new version, where "labels" are no longer working via an issue template. We will hunt down what is going on. In the meantime, we will process your request manually :)

**Comment by LubosKolouch** [comment]
![image](https://user-images.githubusercontent.com/4145223/94794513-44639f00-03dc-11eb-8e13-e102ec9dee4c.jpeg)

**Comment by TrueBrain** [comment]
Good news, @LubosKolouch, your request has been approved!
You now have access to cs_CZ.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before your membership is updated.

You can login to [eints ](https://translator.openttd.org/language/cs_CZ) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/cs_CZ).

Sorry again for the trouble!
