### ISSUE TITLE
[cs_CZ] Translator access request

### ISSUE THREAD

**Issue by TheSuperPowerCoder123** [OpenTTD/team#295]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Czech**.

The **Czech** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Also my name is David and i'm a young programmer from czech republic 

Thank you,

**Comment by DorpsGek** [comment]
Good news, @TheSuperPowerCoder123, your request has been approved!
You now have access to cs_CZ.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/cs_CZ) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/cs_CZ).
