### ISSUE TITLE
[sr_RS] Translator access request

### ISSUE THREAD

**Issue by itmcomputers** [OpenTTD/team#298]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Serbian**.

The **Serbian** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

I am natural born Serbian citizen, and so I would like to participate and help about translating

Thank you,

**Comment by DorpsGek** [comment]
Good news, @itmcomputers, your request has been approved!
You now have access to sr_RS.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/sr_RS) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/sr_RS).
