### ISSUE TITLE
[de_DE] Translator access request

### ISSUE THREAD

**Issue by jdopss** [OpenTTD/team#346]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **German**.

Ich habe gute Englisches Übersetzungswissen und bin auch ein Deutscher

Thank you,

**Comment by DorpsGek** [comment]
I am really sorry, @jdopss, but it seems you modified the template.
Please only add text after the second marker.
Anything you modify before will result in this reply, and closure of your ticket.

I am really sorry, but I have to be strict about this.

Please open a new issue from a template, and only add text after the second marker.
Thank you for your understanding.
