### ISSUE TITLE
[ja_JP] Translator access request

### ISSUE THREAD

**Issue by fmang** [OpenTTD/team#401]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Japanese**.

The **Japanese** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Though I am not native in either English or Japanese, I believe I am proficient enough to make accurate translations. I live in Japan and use Japanese as my primary language. I also have a native Japanese speaker and casual OpenTTD player by my side willing to review my changes.

Thank you.

**Comment by DorpsGek** [comment]
Thank you @fmang for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @fmang is requesting access to language [__ja_JP__](https://github.com/orgs/OpenTTD/teams/ja_JP).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @fmang, your request has been approved!
You now have access to ja_JP.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/ja_JP) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/ja_JP).
