### ISSUE TITLE
[it_IT] Translator access request

### ISSUE THREAD

**Issue by Barto00** [OpenTTD/team#409]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Italian**.

The **Italian** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

I'm Italian so i know pretty well the language. If you need something, feel free to contact me, even if i'm actually studying in university, so i obviously can't pass the whole day translating the game, but i promise i will help with whenever you need some help.

Thank you,

**Comment by DorpsGek** [comment]
Thank you @Barto00 for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @Barto00 is requesting access to language [__it_IT__](https://github.com/orgs/OpenTTD/teams/it_IT).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by TrueBrain** [comment]
/deny

I am really sorry, but you failed the turing test :(
