### ISSUE TITLE
No ka_GE language for translation/Georgian addition

### ISSUE THREAD

**Issue by NorwayFun** [OpenTTD/team#415]
Hello,
Wanted to translated OpenTTD to Georgian, but unfortunately there is no ka_GE language code available on website/github to request access to it.

Could you add Georgian or point me to right person, please?

Temuri

**Comment by TrueBrain** [comment]
Please see https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md#i-want-to-add-an-entirely-new-translation-language for more information on how to set that in motion. But be careful, it is a lot of work!

Going to close this ticket here now; but after you read the above link and considered it, feel free to follow those instructions how to proceed next :) Tnx!

**Comment by NorwayFun** [comment]
If there would be 100m Georgians, it would be quite different world Around :)))
Anyways, I'll first try to get it in more than 20% translation and will get back :)
Thank you :)


Temuri
