### ISSUE TITLE
[fil_PH] Translator access request

### ISSUE THREAD

**Issue by IverCoder** [OpenTTD/team#419]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Filipino**.

The **Filipino** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

I hope I can join translations even if there is no team for my language yet.

Thank you,
@IverCoder

**Comment by IverCoder** [comment]
Apparently I'm the first one to volunteer for this language...

**Comment by glx22** [comment]
The language doesn't exist yet in openttd, so it will first require to be added to the game before being supported by web translator.

**Comment by IverCoder** [comment]
> The language doesn't exist yet in openttd, so it will first require to be added to the game before being supported by web translator.

Oh, do I need to take further action for the language to be added ingame?

**Comment by TrueBrain** [comment]
Please see https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md#i-want-to-add-an-entirely-new-translation-language for more information on how to set that in motion. But be careful, it is a lot of work!

Going to close this ticket here now; but after reading the above link and considering it, feel free to follow those instructions how to proceed next :) Tnx!

**Comment by IverCoder** [comment]
> Please see https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md#i-want-to-add-an-entirely-new-translation-language for more information on how to set that in motion. But be careful, it is a lot of work!
> 
> Going to close this ticket here now; but after you read the above link and considered it, feel free to follow those instructions how to proceed next :) Tnx!

Thank you! Will look to it tomorrow.
