### ISSUE TITLE
[tr_TR] Translator access request

### ISSUE THREAD

**Issue by BeratSJ** [OpenTTD/team#425]
Hi,I'm Berat

I would like to ask for access to help translating OpenTTD and its subprojects into **Turkish**.

The **Turkish** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

There are minor glitches in the Turkish language of the game, even if not much. (As far as I can see) That's why I would like to improve the Turkish language of the game. I also noticed that many pages of the game's website were not translated into Turkish. (eg: Development Page) I can fix it if you let me.

Thank you.

**Comment by DorpsGek** [comment]
I am really sorry, @BeratSJ, but it seems you modified the template.
Please only add text after the second marker.
Anything you modify before will result in this reply, and closure of your ticket.

I am really sorry, but I have to be strict about this.

Please open a new issue from a template, and only add text after the second marker.
Thank you for your understanding.
