### ISSUE TITLE
[tr_TR] Translator access request

### ISSUE THREAD

**Issue by BeratSJ** [OpenTTD/team#426]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Turkish**.

The **Turkish** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

There are minor glitches in the Turkish language of the game, even if not much. (As far as I can see) That's why I would like to improve the Turkish language of the game. I also noticed that many pages of the game's website were not translated into Turkish. (eg: Development Page) I can fix it if you let me.
Thank you,

**Comment by DorpsGek** [comment]
Thank you @BeratSJ for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @BeratSJ is requesting access to language [__tr_TR__](https://github.com/orgs/OpenTTD/teams/tr_TR).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @BeratSJ, your request has been approved!
You now have access to tr_TR.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/tr_TR) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/tr_TR`.
