### ISSUE TITLE
[fr_FR] Translator access request

### ISSUE THREAD

**Issue by Lishouuu** [OpenTTD/team#429]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **French**.

The **French** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

I speak French fluently and I'm willing to help make this game a more accessible place
Thank you,
Lishouuu

**Comment by DorpsGek** [comment]
Good news, @Lishouuu, your request has been approved!
You now have access to fr_FR.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/fr_FR) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/fr_FR`.
