### ISSUE TITLE
[fr_FR] Translator access request

### ISSUE THREAD

**Issue by Naeso** [OpenTTD/team#430]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **French**.

I'm native and I already translated the Parallel Launcher software in French (from English US). I've noticed a few errors in the French translation of OpenTTD and I would like to fix them.

Thank you,

**Comment by DorpsGek** [comment]
I am really sorry, @Naeso, but it seems you modified the template.
Please only add text after the second marker.
Anything you modify before will result in this reply, and closure of your ticket.

I am really sorry, but I have to be strict about this.

Please open a new issue from a template, and only add text after the second marker.
Thank you for your understanding.
