### ISSUE TITLE
[cy_GB] Translator access request

### ISSUE THREAD

**Issue by Ansbaradigeidfran** [OpenTTD/team#432]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Welsh**.

The **Welsh** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Thank you,

It's been a few years since I last made contributions (and you've migrated the webtranslator to github in the meantime), but I'd like to pick it up again.

Geraint

**Comment by DorpsGek** [comment]
Good news, @Ansbaradigeidfran, your request has been approved!
You now have access to cy_GB.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/cy_GB) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/cy_GB`.
