### ISSUE TITLE
[en_US] Translator access request

### ISSUE THREAD

**Issue by Gadg8eer** [OpenTTD/team#435]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **English (US)**.

The **English (US)** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Thank you,
Gadg8eer

P.S. I promise I actually have a well-intentioned, if minor, reason for this, see issues #4415 and #11123. I really do want to earn back trust from this community, if it will get my username unbanned from TT-Forums, and I figure this is one of the few ways I can contribute that will do so.

**Comment by DorpsGek** [comment]
Thank you @Gadg8eer for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @Gadg8eer is requesting access to language [__en_US__](https://github.com/orgs/OpenTTD/teams/en_US).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by frosch123** [comment]
I am sorry, we do not want to extend forum disputes into translations.
