### ISSUE TITLE
[cs_CZ] Translator access request

### ISSUE THREAD

**Issue by JakMel** [OpenTTD/team#441]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Czech**.

The **Czech** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Some strings in the **Czech** language are translated in a misleading or inaccurate way and I would like to contribute to polishing them to perfection. Players probably know or quickly figure out what a given text means or what a given button does, but I think the goal should be precise wording and perfectly understandable language.

Thank you, 
JakMel

**Comment by DorpsGek** [comment]
Thank you @JakMel for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @JakMel is requesting access to language [__cs_CZ__](https://github.com/orgs/OpenTTD/teams/cs_CZ).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @JakMel, your request has been approved!
You now have access to cs_CZ.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/cs_CZ) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/cs_CZ`.
