### ISSUE TITLE
[ta_IN] Translator access request

### ISSUE THREAD

**Issue by Jeyanthinath** [OpenTTD/team#462]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Tamil**.

The **Tamil** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

I am native Tamil speaker, and I have already contributed to many other software in Tamil translation. I would love to make more and more games / software accessible for Tamil folks.  

Thank you,

**Comment by DorpsGek** [comment]
Thank you @Jeyanthinath for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @Jeyanthinath is requesting access to language [__ta_IN__](https://github.com/orgs/OpenTTD/teams/ta_IN).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @Jeyanthinath, your request has been approved!
You now have access to ta_IN.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/ta_IN) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/ta_IN`.
