### ISSUE TITLE
[zh_TW] Translator access request

### ISSUE THREAD

**Issue by WenSimEHRP** [OpenTTD/team#474]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Chinese (Traditional)**.

The **Chinese (Traditional)** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

*I only have limited experience with using Traditional Chinese, and the reason why I am asking for access is because I found a bug in the translations that could be fixed by anyone.*

Thank you,

**Comment by DorpsGek** [comment]
Thank you @WenSimEHRP for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @WenSimEHRP is requesting access to language [__zh_TW__](https://github.com/orgs/OpenTTD/teams/zh_TW).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by glx22** [comment]
I don't have any issue to add you as translator, even for one fix, but maybe you can try opening a discussion (tagging `@OpenTTD/zh_TW`) to make them aware of the issue and see if it's enough.
