### ISSUE TITLE
[it_IT] Translator access request

### ISSUE THREAD

**Issue by Etneus95** [OpenTTD/team#477]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Italian**.

The **Italian** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Hey. I'm a longtime player with recent experience in translation of websites and projects in Italian. I'll be more than happy to contribute to OpenTTD!
Thank you,

**Comment by DorpsGek** [comment]
Good news, @Etneus95, your request has been approved!
You now have access to it_IT.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/it_IT) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/it_IT`.
