### ISSUE TITLE
[sv_SE] Translator access request

### ISSUE THREAD

**Issue by daishan-swe** [OpenTTD/team#483]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Swedish**.

The **Swedish** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Thank you,
Peter

**Comment by DorpsGek** [comment]
Thank you @daishan-swe for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @daishan-swe is requesting access to language [__sv_SE__](https://github.com/orgs/OpenTTD/teams/sv_SE).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.
