### ISSUE TITLE
[eo_EO] Translator access request

### ISSUE THREAD

**Issue by JadedCtrl** [OpenTTD/team#484]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Esperanto**.

The **Esperanto** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

In the past, I’ve contributed Esperanto translations to other libre projects, most notably [Element](https://translate.element.io/user/detruita/) (using Weblate), [Haiku](https://i18n.haiku-os.org/pootle/user/jaidedpts/) [[stats](https://i18n.haiku-os.org/pootle/user/jaidedpts/stats/detailed?month=2020-04)], and some third-party Haiku software like [Calendar](https://github.com/HaikuArchives/Calendar/pull/52). I haven’t been too active over the past couple of years, only doing small copy-editing here and there — though I’d like to be more active! Lately I’ve been translating and/or adding i18n support to [Minetest](https://github.com/minetest/minetest/pull/14215) and Minetest mods like [ambience](https://codeberg.org/tenplus1/ambience/pulls/1), [connected_chests](https://github.com/HybridDog/connected_chests/pull/10), [skinsdb](https://github.com/minetest-mods/skinsdb/pull/95), [3d_armor](https://github.com/minetest-mods/3d_armor/pull/128), [minetest_doc](https://codeberg.org/Wuzzy/minetest_doc/pulls/3), etc.

Thank you,
jadedctrl

**Comment by DorpsGek** [comment]
Thank you @JadedCtrl for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @JadedCtrl is requesting access to language [__eo_EO__](https://github.com/orgs/OpenTTD/teams/eo_EO).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @JadedCtrl, your request has been approved!
You now have access to eo_EO.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/eo_EO) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/eo_EO`.
