### ISSUE TITLE
[fi_FI] Translator access request

### ISSUE THREAD

**Issue by Finjet-cyber** [OpenTTD/team#493]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Finnish**.

The **Finnish** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Thank you, ja terve vaan! Suomi sujuu.

**Comment by DorpsGek** [comment]
Thank you @Finjet-cyber for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @Finjet-cyber is requesting access to language [__fi_FI__](https://github.com/orgs/OpenTTD/teams/fi_FI).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by frosch123** [comment]
You already have access. Please log-out/log-in to the translator agian.

**Comment by Finjet-cyber** [comment]
My mistake, thank you for pointing that out.

ma 5. helmik. 2024 klo 22.35 frosch ***@***.***) kirjoitti:
