### ISSUE TITLE
[tr_TR] Translator access request

### ISSUE THREAD

**Issue by metsysma** [OpenTTD/team#494]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Turkish**.

The **Turkish** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

I did translator work before and native Turkish. I would love to translate.
Thank you,
BR
Metsy

**Comment by DorpsGek** [comment]
Good news, @metsysma, your request has been approved!
You now have access to tr_TR.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/tr_TR) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/tr_TR`.
