### ISSUE TITLE
[pl_PL] Translator access request

### ISSUE THREAD

**Issue by SzyZuu** [OpenTTD/team#508]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Polish**.

The **Polish** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

I'm a native polish speaker with a lot of experience in the English language, therefore I am hoping to help with the translations

Thank you,
SzyZu

**Comment by DorpsGek** [comment]
Good news, @SzyZuu, your request has been approved!
You now have access to pl_PL.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/pl_PL) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/pl_PL`.
