### ISSUE TITLE
[sv_SE] Translator access request

### ISSUE THREAD

**Issue by MaxPetersson** [OpenTTD/team#546]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Swedish**.

The **Swedish** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Never worked on something similare before. However, I have lived in Sweden for 35 years (born and raised) and I love Railroad Tycoon, Transport Fever, Sid Meier's Railroads, ... list goes on.

Thank you,

**Comment by DorpsGek** [comment]
Good news, @MaxPetersson, your request has been approved!
You now have access to sv_SE.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/sv_SE) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/sv_SE`.
