### ISSUE TITLE
[bg_BG] Translator access request

### ISSUE THREAD

**Issue by Alexandar83** [OpenTTD/team#577]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Bulgarian**.

The **Bulgarian** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

More about me:
-The Bulgarian is my native language and I'm quite proficient at it's grammar
-A huge fan of the TT game and the OpenTTD project
-A professional developer for 14 years
-Highly proficient in English
-Willing to give my contribution to this wonderful project (I would only have time for the translation part :) )

Thank you,

**Comment by DorpsGek** [comment]
Thank you @Alexandar83 for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @Alexandar83 is requesting access to language [__bg_BG__](https://github.com/orgs/OpenTTD/teams/bg_BG).

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @Alexandar83, your request has been approved!
You now have access to bg_BG.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before proceeding.

After accepting the invitation, you will be able to login to [eints](https://translator.openttd.org/language/bg_BG) to start working on the translation.
Also check out the [translator discussions](https://github.com/OpenTTD/team/discussions). When starting a new discussion, make sure to tag your team using `@OpenTTD/bg_BG`.
