### ISSUE TITLE
[af_ZA] Translator access request

### ISSUE THREAD

**Issue by Doctor420UK** [OpenTTD/team#591]
```
```
> > > > ``````
```
```
@matthijskooijman 
Hi,

I would like to ask for access~~~~ to help translating OpenTTD and its subprojects into **Afrikaans**.

The **Afrikaans** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

<!-- Please do not edit the above message. Do feel free to add a personal note after this line. -->

Thank you,

**Comment by DorpsGek** [comment]
I am really sorry, @Doctor420UK, but it seems you modified the template.
Please only add text after the second marker.
Anything you modify before will result in this reply, and closure of your ticket.

I am really sorry, but I have to be strict about this.

Please open a new issue from a template, and only add text after the second marker.
Thank you for your understanding.

**Comment by Doctor420UK** [comment]
- [ ]

**Comment by DorpsGek** [comment]
I am really sorry, @Doctor420UK, but it seems you modified the template.
Please only add text after the second marker.
Anything you modify before will result in this reply, and closure of your ticket.

I am really sorry, but I have to be strict about this.

Please open a new issue from a template, and only add text after the second marker.
Thank you for your understanding.
