### ISSUE TITLE
[de_DE] Translator access request

### ISSUE THREAD

**Issue by Eddi-z** [OpenTTD/team#6]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **German**.

The **German** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

this is some editing

Thank you,

**Comment by DorpsGek** [comment]
Thank you @Eddi-z for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @Eddi-z is requesting access to language __de_DE__.

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @Eddi-z, your request has been approved!
You now have access to de_DE.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before your membership is updated.

You can login to [eints](https://translator.openttd.org/language/de_DE) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/de_DE).
