### ISSUE TITLE
[pt_BR] Translator access request

### ISSUE THREAD

**Issue by JuniuSeifero** [OpenTTD/team#69]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **Portuguese (Brazilian)**.

The **Portuguese (Brazilian)** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Hi! I am a native brazilian, and i LOVE OpenTTD! It would be an honor to me being part of the translation team!

Thank you,

Luiz Carlos

**Comment by DorpsGek** [comment]
Good news, @JuniuSeifero, your request has been approved!
You now have access to pt_BR.

If you are not a member of OpenTTD yet, you will receive an invitation shortly (or click [here](https://github.com/orgs/OpenTTD/invitation)).
You will have to accept this invitation before your membership is updated.

You can login to [eints](https://translator.openttd.org/language/pt_BR) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/pt_BR).
